name: TestPipelines 

on: 
  push:
    branches:    
      - main

jobs:
  deploy:
    name: TestPipelines
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_15.4.app
        
      - name: Running Xcode Version
        run: /usr/bin/xcodebuild -version

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install

      - name: List files in root directory
        run: |
          ls -la

      - name: Run Unit Tests
        continue-on-error: false  # Fail the workflow if tests fail
        run: |
          if [ -f "TestPipelines.xcworkspace" ]; then
            xcodebuild test -scheme TestPipelines \
              -destination 'platform=iOS Simulator,name=iPhone 14' | xcpretty
          elif [ -f "TestPipelines.xcodeproj" ]; then
            xcodebuild test -scheme TestPipelines \
              -destination 'platform=iOS Simulator,name=iPhone 14' | xcpretty
          else
            echo "Neither .xcworkspace nor .xcodeproj found for testing."
            exit 1
          fi

      - name: Archive the App
        env:
          BUILD_DIR: "$GITHUB_WORKSPACE/TestPipelines/build"
          ACTION: "build"
        run: |
          if [ -f "TestPipelines.xcworkspace" ]; then
            xcodebuild archive -workspace TestPipelines.xcworkspace \
              -scheme TestPipelines \
              -configuration Release \
              -archivePath "$GITHUB_WORKSPACE/TestPipelines.xcarchive" \
              -destination 'generic/platform=iOS Simulator'
          elif [ -f "TestPipelines.xcodeproj" ]; then
            xcodebuild archive -project TestPipelines.xcodeproj \
              -scheme TestPipelines \
              -configuration Release \
              -archivePath "$GITHUB_WORKSPACE/TestPipelines.xcarchive" \
              -destination 'generic/platform=iOS Simulator'
          else
            echo "Neither .xcworkspace nor .xcodeproj found for archiving."
            exit 1
          fi

      - name: Verify archive path
        run: |
          if [ -d "$GITHUB_WORKSPACE/TestPipelines.xcarchive" ]; then
            echo "Archive found!"
          else
            echo "Archive not found at expected location."
            exit 1
          fi
