name: iOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CocoaPods
      run: sudo gem install cocoapods

    - name: Clean Build Folder
      run: |
        xcodebuild clean -workspace TestPipelines.xcworkspace -scheme TestPipelines

    - name: Remove Derived Data
      run: rm -rf ~/Library/Developer/Xcode/DerivedData/*

    - name: Reintegrate Pods and Install New One
      run: |
        pod deintegrate
        pod install
    
    - name: Build the project
      run: |
        xcodebuild -workspace TestPipelines.xcworkspace \
          -scheme TestPipelines \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          clean build
        
    # - name: Verify directory and Run Unit Tests
    - name: Running the Unit Tests
      run: |
         echo "Verifying the presence of .xcworkspace file"
          xcodebuild test -workspace TestPipelines.xcworkspace \
          -scheme TestPipelines \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          else
            echo ".xcworkspace file not found for testing."
            exit 1
          fi

    - name: Archive the App
      env:
          BUILD_DIR: "$GITHUB_WORKSPACE/TestPipelines/build"
          ACTION: "build"
        run: |
          xcodebuild archive -workspace TestPipelines.xcworkspace \
            -scheme TestPipelines \
            -configuration Release \
            -archivePath "$GITHUB_WORKSPACE/TestPipelines.xcarchive" \
            -destination 'generic/platform=iOS Simulator'

    - name: Verify archive path
      run: |
          if [ -d "$GITHUB_WORKSPACE/TestPipelines.xcarchive" ]; then
            echo "Archive found!"
          else
            echo "Archive not found at expected location."
            exit 1
          fi